### ISSUE TITLE
deprecated behavior of torch.symeig in newer PyTorch

### ISSUE THREAD

**Issue by vlawhern** [yuxi120407/DIB#1]
Hi,

I recently ran into your ICASSP paper and thought it was pretty interesting; thanks for sharing the code.

I just wanted to point out that in newer PyTorch versions (I'm using 1.10) I get the following warning:

```
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272128894/work/aten/src/ATen/native/BatchLinearAlgebra.cpp:2499.)
  eigv = torch.abs(torch.symeig(k, eigenvectors=True)[0])

```

In particular a major change is in ```torch.symeig``` that now takes the lower triangular portion by default instead of the upper which seems like a pretty big change. In your code (https://github.com/yuxi120407/DIB/blob/main/utils.py#L33, and in other spots) it appears you don't set a default which could mean the code's behavior could drastically change because of this.

What changes are needed in the code to avoid these warnings in newer PyTorch versions? Is the suggested change listed above sufficient?

**Comment by yuxi120407** [comment]
I think you can replace torch.symeig to the following:
eigv = torch.abs(torch.linalg.eigh(k, UPLO="U")[0]).
If you have any other issues, please let me know.
