### ISSUE TITLE
Pairwise distance calculation for RBF kernel

### ISSUE THREAD

**Issue by mcd4874** [yuxi120407/DIB#2]
I do not understand the logic behind the pairwise_distance(x) function. Does this function try to implement the p-norm distance between every pair of row vectors in the input and generate a 128x128 matrix? I run torch.nn.functional.pdist to calculate p-norm distance between every pair, but I do not get the same result as the pairwise_distances logic.

A simple way to generate an NxN matrix with pairwise_distance in pytorch is  matrix = torch.cdist(x[None, :, :], x[None,:,:])[0]. 

in utils.py

def pairwise_distances(x):
    #x should be two dimensional
    x = x.view(128,-1)
    instances_norm = torch.sum(x**2,-1).reshape((-1,1))
    return -2*torch.mm(x,x.t()) + instances_norm + instances_norm.t()

in the main.py file

IXZ = calculate_MI(inputs,Z,s_x=1000,s_y=sigma**2)

Why is the kernel width of the input image 1000? I believe the calculation from the paper mentions, "For each sample, we evaluate its k (k = 10) nearest distances and take the mean. We choose kernel width  as the average mean value for all samples."

**Comment by yuxi120407** [comment]
Thanks for your reading my work. 
Yes, the pairwise_distnce is to calculate the gram matrix, the size of which is NxN. 
There are many different ways to calculate the pairwise distance matrix, you can choose what you like.
For the kernel width, I modify my codes and use the same way to estimate the kernel size of the input.
